version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_SETTINGS_ENV=Production
      - DATABASE_URL=postgres://marc:admin@db:5432/adoptable_db
      - USE_MINIO=TRUE
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_STORAGE_BUCKET_NAME=public
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: adoptable_db
      POSTGRES_USER: marc
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

    networks:
      - app_network

  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data

networks:
  app_network:

volumes:
  postgres_data:
  minio_data:
