version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_SETTINGS_ENV=Production
      - DATABASE_URL=postgres://marc:admin@db:5432/adoptable_db
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: adoptable_db
      POSTGRES_USER: marc
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

volumes:
  postgres_data:
