# Generated by Django 5.1.6 on 2025-05-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
