# Generated by Django 5.1.6 on 2025-03-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
