# Generated by Django 5.1.6 on 2025-05-03 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='since',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
