# Generated by Django 5.1.6 on 2025-05-13 07:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_adoptionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together={('user', 'animal')},
        ),
    ]
