# Generated by Django 5.1.6 on 2025-02-28 07:49

import app.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopterprofile',
            name='avatar',
            field=models.ImageField(storage=app.storages.PrivateMediaStorage(), upload_to='profile_images/'),
        ),
    ]
