# Generated by Django 5.1.6 on 2025-03-16 12:16

import app.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_adopterprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopterprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=app.storages.PrivateMediaStorage(), upload_to='profile_images/'),
        ),
    ]
