# Generated by Django 5.1.6 on 2025-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_adopterprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopterprofile',
            name='adoption_form',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
