# .github/workflows/ci.yml

name: CI

on:
  push: {}
  pull_request: {}

jobs:
  # -------------------------------------------------------
  # JOB: Backend (Django + Poetry + Linters + Tests + Coverage)
  # -------------------------------------------------------
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: adoptable_db
          POSTGRES_USER: marc
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U marc -d adoptable_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB_NAME: adoptable_db
      POSTGRES_USER: marc
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

      DJANGO_SECRET_KEY: dummy-secret-key
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost"

      EMAIL_HOST: smtp.example.com
      EMAIL_PORT: "587"
      EMAIL_USE_TLS: "True"
      EMAIL_HOST_USER: dummy@example.com
      EMAIL_HOST_PASSWORD: dummy-password
      DEFAULT_FROM_EMAIL: dummy@example.com

      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_NO_INTERACTION: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies (backend)
        working-directory: ./backend
        run: poetry install --no-root

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U marc -d adoptable_db; do
            echo "Esperando a Postgres…"
            sleep 2
          done

      - name: Run black check (backend)
        working-directory: ./backend
        run: poetry run black --check .

      - name: Run flake8 (backend)
        working-directory: ./backend
        run: poetry run flake8 --config .flake8 .

      - name: Run isort check (backend)
        working-directory: ./backend
        run: poetry run isort --check-only .

      - name: Run migrations (backend)
        working-directory: ./backend
        run: python manage.py migrate

      - name: Run Django tests with coverage
        working-directory: ./backend
        run: |
          coverage run --source='.' manage.py test
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/coverage.xml
          fail_ci_if_error: true

  # -------------------------------------------------------
  # JOB: Frontend (Vite + Node + Linters + Tests + Build)
  # -------------------------------------------------------
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        working-directory: ./adoptable_front
        run: npm install

      - name: Run ESLint (frontend)
        working-directory: ./adoptable_front
        run: npm run lint

      - name: Build production bundle (frontend)
        working-directory: ./adoptable_front
        run: npm run build
