on:
  push:
    branches: [main, frontend-login-create]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          cd backend
          poetry install

      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=my_django_project.settings" >> $GITHUB_ENV
        # Agrega otras variables si son necesarias:
        # echo "DATABASE_URL=sqlite:///db.sqlite3" >> $GITHUB_ENV

      - name: Run migrations
        run: |
          cd backend
          poetry run python manage.py migrate

      - name: Run backend tests
        run: |
          cd backend
          poetry run pytest --ds=my_django_project.settings --disable-warnings

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm run test
